### ISSUE TITLE
Script not create AP..

### ISSUE THREAD

**Issue by Qurexhi** [B4ckP0r7/RogueSploit#1]
when i start to create AP the script restart any solution??

**Comment by B4ckP0r7** [comment]
Do you have hostapd installed? Which os are you using? Do you have an external interface? Named wlan1? At the moment my script accept only wlan1 interfaces but I'll add a modifiable interface at the start :) just wait; sorry for the inconvenience

**Comment by Qurexhi** [comment]
i'm using kali linux latest version

**Comment by Qurexhi** [comment]
how to set wlan0. can you make video tutorial for us??

**Comment by dinamite01** [comment]
hello ,i have the same problem when i start to create AP the script restart any solution??

**Comment by B4ckP0r7** [comment]
Please be patient, I'm fixing the problem :)
Soon I'll do a video for demonstration and for the mitmf installation "bug" :)
I'm adding Airbase-ng as network method.
You'll be able to choose from airabase-ng and hostapd :)
But I'm thinking to remove hostapd because it have many hardware problems; also with network-manager.
Have a nice day!

**Comment by dinamite01** [comment]
ok , i waiting I look forward to it 
great

**Comment by B4ckP0r7** [comment]
Thanks for the patient :D

**Comment by dmcxbluecoder** [comment]
Yep same her eI added wlan1 but it doesnt seem to accept it as it reads no such device Great script hopefully it will work its awesome keep it up

**Comment by B4ckP0r7** [comment]
don't panic, i'm just working on it :D

**Comment by B4ckP0r7** [comment]
Fixed, now you can choose interface and fake ap name.
Hostapd and newtork manager conflicts are fixed now, enjoy
